name: 'Filter issue by label'
description: 'Checks if an issue has a label'
inputs:
  labels:  # labels we need to proceed
    description: 'An array of labels needed to proceed'
    required: true
    default: ""
  type:  # match type
    description: 'can be "any" or "all"'
    required: true
    default: "any"
outputs:
  match: # was there a match?
    description: 'True if one of the labels matched. False if not.'
runs:
  using: 'node12'
  main: 'index.js'
